### ISSUE TITLE
[Bug]: Unable to untag a post

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#544]
### Describe the bug

Clicking on a post's tag that I added removes it from the UI but the tag comes back on page refresh.

### Reproduce

1. Find a post in the feed (or create a new one)
2. Add a tag to the post
3. Refresh the page just to be sure local cache is not the issue
4. Click on the post's tag that was just added, it disappears
5. Refresh the page
6. Observe the tag is back

### Web Browser

Version 1.71.121 Chromium: 130.0.6723.91 (Official Build) (64-bit)

### Pubky App Version

pubky-nexus v0.1.0

**Comment by flaviomoceri** [comment]
fixed, next release https://github.com/pubky/pubky-app/pull/549
deleteTag
deleteTagProfile

**Comment by catch-21** [comment]
On current staging deployment, I cannot seem to permanently delete tags made to a post.


https://github.com/user-attachments/assets/808ed656-831c-49a8-9c65-03c7842e8df4


https://github.com/user-attachments/assets/7da94c42-eccb-47b7-9566-93dcccca8633

**Comment by flaviomoceri** [comment]
@catch-21 It works, if you create a tag, reload the page, remove the tag and reload the page everything works correctly

The problem is caused by the fact that if you create and delete a tag immediately after, the tag is only visible locally but in fact does not exist yet and is not deleted

it is a problem related to instantaneity, I will assign Miguel

**Comment by flaviomoceri** [comment]
But you can create/remove a tag without any problems, so maybe change the title of the issue

**Comment by catch-21** [comment]
Tested in 342cb8fac3f51c92ea9375fabe45df5940b879a4
Besides the refresh thing that is tracked by https://github.com/pubky/pubky-app/issues/493,I think this is ok now.
